name: Create a release
on: [push]
jobs:
  check-commit:
    name:  Check If commit is deploy trigger
    runs-on: ubuntu-latest
    steps: 
      - name: Extract version number
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '.*(v\d+\.\d+\.\d+).*'
      - name: Stop CI if not release
        if: ${{ steps.version.outputs.match == '' }}
        uses: andymckay/cancel-action@0.2
      - name: Create Release
        if: ${{ steps.version.outputs.match != '' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.version.outputs.group1 }}
          title: Version ${{ steps.version.outputs.group1 }}
  build-and-release:
    name: ${{ matrix.platform }} Build
    runs-on: ubuntu-latest
    needs: check-commit
    environment: Release
    strategy:
      matrix:
        platform: [StandaloneWindows, StandaloneWindows64, StandaloneLinux64]
    steps:
      - name: Checkout dev Git branch
        uses: actions/checkout@v2
      - name: Tests and Debug
        run: ls -lsa
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Game-${{ matrix.platform }}
          restore-keys: Library-
      - name: Build the game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.platform }}
      - name: Extract version number
        id: version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '.*(v\d+\.\d+\.\d+).*'
      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: Build.zip
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build.zip
          asset_name: ${{ matrix.platform }}.zip
          tag: ${{ steps.version.outputs.group1 }}