name: Create a release
on: 
  push:
    tags:
      - "v*"
jobs:
  build-and-release:
    name: "Git tag Release"
    runs-on: "ubuntu-latest"
    environment: Release
    strategy:
      matrix:
        platform: [StandaloneWindows, StandaloneWindows64, StandaloneLinux64]
    steps:
      - name: Checkout dev Git branch
        uses: actions/checkout@v2
      - name: Tests and Debug
        run: ls -lsa
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Game-${{ matrix.platform }}
          restore-keys: |
            Library-MyProjectName-
            Library-
      - name: Build the game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.platform }}
      - name: Extract tag name
        id: tag
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
          echo ${GITHUB_REF/refs\/tags\/v/} > VERSION.TXT
          ls -lsa
          cat VERSION.TXT
      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: ${{ matrix.platform }}-${{ steps.tag.outputs.VERSION }}.zip
      - name: "Create a release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            VERSION.txt
            ${{ matrix.platform }}-${{ steps.tag.outputs.VERSION }}.zip