name: Create a release
on: [push]
jobs:
  check-commit:
    name:  Check If commit is deploy trigger
    runs-on: ubuntu-latest
    steps: 
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: 'v\d+\.\d+\.\d+\.?\d*'
          flags: 'gm'
          error: 'Your commit message shpud contain "vX.X.X" to trigger a deploy.'
  build-and-release:
    name: Build the Game and upload the files
    runs-on: ubuntu-latest
    environment: Release
    strategy:
      matrix:
        platform: [StandaloneWindows, StandaloneWindows64, StandaloneLinux64]
    steps:
      - name: Checkout dev Git branch
        uses: actions/checkout@v2
      - name: Tests and Debug
        run: ls -lsa
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Game-${{ matrix.platform }}
          restore-keys: Library-
      - name: Build the game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.platform }}
      - name: Extract version number
        id: version
        uses: actions-ecosystem/action-add-labels@v1
        with:
          text: ${{ github.event.head_commit.message }}
          regex: 'v(\d+\.\d+\.\d+)\.?\d*'
      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: Build.zip
      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build.zip
          asset_name: ${{ matrix.platform }}.zip
          tag: ${{ steps.version.outputs.group1 }}